---
name: release-please
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions: {}
jobs:
  release-please:
    uses: SchweizerischeBundesbahnen/github-workflows-polarion/.github/workflows/reusable-release-please.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      release-type: maven
      target-branch: ${{ github.ref_name }}
